spring.application.name=Coding-Assistance

# Anthropic Claude Configuration
spring.ai.anthropic.api-key=${CLAUDE_API_KEY:}
spring.ai.anthropic.chat.options.model=claude-3-haiku-20240307
spring.ai.anthropic.chat.options.temperature=0.7
spring.ai.anthropic.chat.options.max-tokens=1000

spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-2.0-flash
spring.ai.google.genai.chat.options.temperature=0.5

# Ollama Configuration # qwen3:1.7b  # llama3.2:3b
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:3b
spring.ai.ollama.chat.options.temperature=0.7

spring.ai.openai.api-key=
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
#llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.7

spring.ai.huggingface.chat.api-key=
spring.ai.huggingface.chat.url=

